// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor_user_id, action, resource_type, resource_id, scope_type, scope_id, old_value, new_value, ip_hash, user_agent_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, actor_user_id, action, resource_type, resource_id, scope_type, scope_id, old_value, new_value, ip_hash, user_agent_hash, created_at
`

type CreateAuditLogParams struct {
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
	Action        string      `json:"action"`
	ResourceType  string      `json:"resource_type"`
	ResourceID    pgtype.UUID `json:"resource_id"`
	ScopeType     *string     `json:"scope_type"`
	ScopeID       *string     `json:"scope_id"`
	OldValue      []byte      `json:"old_value"`
	NewValue      []byte      `json:"new_value"`
	IpHash        *string     `json:"ip_hash"`
	UserAgentHash *string     `json:"user_agent_hash"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ScopeType,
		arg.ScopeID,
		arg.OldValue,
		arg.NewValue,
		arg.IpHash,
		arg.UserAgentHash,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.ScopeType,
		&i.ScopeID,
		&i.OldValue,
		&i.NewValue,
		&i.IpHash,
		&i.UserAgentHash,
		&i.CreatedAt,
	)
	return i, err
}

const createReviewEvent = `-- name: CreateReviewEvent :one
INSERT INTO review_events (target_type, target_id, actor_user_id, action, old_status, new_status, comment)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, target_type, target_id, actor_user_id, action, old_status, new_status, comment, created_at
`

type CreateReviewEventParams struct {
	TargetType  string      `json:"target_type"`
	TargetID    pgtype.UUID `json:"target_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	OldStatus   *string     `json:"old_status"`
	NewStatus   *string     `json:"new_status"`
	Comment     *string     `json:"comment"`
}

func (q *Queries) CreateReviewEvent(ctx context.Context, arg CreateReviewEventParams) (ReviewEvent, error) {
	row := q.db.QueryRow(ctx, createReviewEvent,
		arg.TargetType,
		arg.TargetID,
		arg.ActorUserID,
		arg.Action,
		arg.OldStatus,
		arg.NewStatus,
		arg.Comment,
	)
	var i ReviewEvent
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.ActorUserID,
		&i.Action,
		&i.OldStatus,
		&i.NewStatus,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}
