// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_user_id, action, resource_type, resource_id, scope_type, scope_id, old_value, new_value, ip_hash, user_agent_hash, created_at
FROM audit_logs
WHERE (
  $1::timestamptz IS NULL OR
  (created_at < $1 OR (created_at = $1 AND id < $2::uuid))
)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListAuditLogsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Limit           int32              `json:"limit"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.CursorCreatedAt, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ScopeType,
			&i.ScopeID,
			&i.OldValue,
			&i.NewValue,
			&i.IpHash,
			&i.UserAgentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
