// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ihks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIHKInfoPage = `-- name: CreateIHKInfoPage :one
INSERT INTO ihk_info_pages (ihk_id, current_text, confidence_level, source_summary, last_version_id, locked, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, ihk_id, current_text, confidence_level, source_summary, last_version_id, locked, updated_by, created_at, updated_at
`

type CreateIHKInfoPageParams struct {
	IhkID           pgtype.UUID `json:"ihk_id"`
	CurrentText     string      `json:"current_text"`
	ConfidenceLevel string      `json:"confidence_level"`
	SourceSummary   *string     `json:"source_summary"`
	LastVersionID   pgtype.UUID `json:"last_version_id"`
	Locked          bool        `json:"locked"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
}

func (q *Queries) CreateIHKInfoPage(ctx context.Context, arg CreateIHKInfoPageParams) (IhkInfoPage, error) {
	row := q.db.QueryRow(ctx, createIHKInfoPage,
		arg.IhkID,
		arg.CurrentText,
		arg.ConfidenceLevel,
		arg.SourceSummary,
		arg.LastVersionID,
		arg.Locked,
		arg.UpdatedBy,
	)
	var i IhkInfoPage
	err := row.Scan(
		&i.ID,
		&i.IhkID,
		&i.CurrentText,
		&i.ConfidenceLevel,
		&i.SourceSummary,
		&i.LastVersionID,
		&i.Locked,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIHKInfoVersion = `-- name: CreateIHKInfoVersion :one
INSERT INTO ihk_info_versions (
  ihk_info_page_id, ihk_id, version_number, old_text, new_text, change_summary, changed_by,
  based_on_info_suggestion_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, ihk_info_page_id, ihk_id, version_number, old_text, new_text, change_summary, changed_by,
  based_on_info_suggestion_id, created_at
`

type CreateIHKInfoVersionParams struct {
	IhkInfoPageID           pgtype.UUID `json:"ihk_info_page_id"`
	IhkID                   pgtype.UUID `json:"ihk_id"`
	VersionNumber           int32       `json:"version_number"`
	OldText                 string      `json:"old_text"`
	NewText                 string      `json:"new_text"`
	ChangeSummary           string      `json:"change_summary"`
	ChangedBy               pgtype.UUID `json:"changed_by"`
	BasedOnInfoSuggestionID pgtype.UUID `json:"based_on_info_suggestion_id"`
}

func (q *Queries) CreateIHKInfoVersion(ctx context.Context, arg CreateIHKInfoVersionParams) (IhkInfoVersion, error) {
	row := q.db.QueryRow(ctx, createIHKInfoVersion,
		arg.IhkInfoPageID,
		arg.IhkID,
		arg.VersionNumber,
		arg.OldText,
		arg.NewText,
		arg.ChangeSummary,
		arg.ChangedBy,
		arg.BasedOnInfoSuggestionID,
	)
	var i IhkInfoVersion
	err := row.Scan(
		&i.ID,
		&i.IhkInfoPageID,
		&i.IhkID,
		&i.VersionNumber,
		&i.OldText,
		&i.NewText,
		&i.ChangeSummary,
		&i.ChangedBy,
		&i.BasedOnInfoSuggestionID,
		&i.CreatedAt,
	)
	return i, err
}

const ensureEmptyIHKInfoPage = `-- name: EnsureEmptyIHKInfoPage :exec
INSERT INTO ihk_info_pages (ihk_id, current_text, confidence_level, source_summary, last_version_id, locked, updated_by)
VALUES ($1, '', 'low', NULL, NULL, false, NULL)
ON CONFLICT (ihk_id) DO NOTHING
`

func (q *Queries) EnsureEmptyIHKInfoPage(ctx context.Context, ihkID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureEmptyIHKInfoPage, ihkID)
	return err
}

const existsIHKBySlugOrNameState = `-- name: ExistsIHKBySlugOrNameState :one
SELECT EXISTS (
  SELECT 1
  FROM ihks
  WHERE is_active = true
    AND (
      slug = $1
      OR (lower(name) = lower($2::text) AND state = $3)
    )
)
`

type ExistsIHKBySlugOrNameStateParams struct {
	Slug  string `json:"slug"`
	Name  string `json:"name"`
	State string `json:"state"`
}

func (q *Queries) ExistsIHKBySlugOrNameState(ctx context.Context, arg ExistsIHKBySlugOrNameStateParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsIHKBySlugOrNameState, arg.Slug, arg.Name, arg.State)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getIHKByID = `-- name: GetIHKByID :one
SELECT id, name, slug, city, state, official_url, is_active, created_at, updated_at
FROM ihks
WHERE id = $1
`

func (q *Queries) GetIHKByID(ctx context.Context, id pgtype.UUID) (Ihk, error) {
	row := q.db.QueryRow(ctx, getIHKByID, id)
	var i Ihk
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.City,
		&i.State,
		&i.OfficialUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIHKInfoPageByIHKID = `-- name: GetIHKInfoPageByIHKID :one
SELECT id, ihk_id, current_text, confidence_level, source_summary, last_version_id, locked, updated_by, created_at, updated_at
FROM ihk_info_pages
WHERE ihk_id = $1
`

func (q *Queries) GetIHKInfoPageByIHKID(ctx context.Context, ihkID pgtype.UUID) (IhkInfoPage, error) {
	row := q.db.QueryRow(ctx, getIHKInfoPageByIHKID, ihkID)
	var i IhkInfoPage
	err := row.Scan(
		&i.ID,
		&i.IhkID,
		&i.CurrentText,
		&i.ConfidenceLevel,
		&i.SourceSummary,
		&i.LastVersionID,
		&i.Locked,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIHKInfoVersionByIDForIHK = `-- name: GetIHKInfoVersionByIDForIHK :one
SELECT id, ihk_info_page_id, ihk_id, version_number, old_text, new_text, change_summary, changed_by,
  based_on_info_suggestion_id, created_at
FROM ihk_info_versions
WHERE id = $1 AND ihk_id = $2
`

type GetIHKInfoVersionByIDForIHKParams struct {
	ID    pgtype.UUID `json:"id"`
	IhkID pgtype.UUID `json:"ihk_id"`
}

func (q *Queries) GetIHKInfoVersionByIDForIHK(ctx context.Context, arg GetIHKInfoVersionByIDForIHKParams) (IhkInfoVersion, error) {
	row := q.db.QueryRow(ctx, getIHKInfoVersionByIDForIHK, arg.ID, arg.IhkID)
	var i IhkInfoVersion
	err := row.Scan(
		&i.ID,
		&i.IhkInfoPageID,
		&i.IhkID,
		&i.VersionNumber,
		&i.OldText,
		&i.NewText,
		&i.ChangeSummary,
		&i.ChangedBy,
		&i.BasedOnInfoSuggestionID,
		&i.CreatedAt,
	)
	return i, err
}

const getNextInfoVersionNumber = `-- name: GetNextInfoVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) + 1 AS next_version
FROM ihk_info_versions
WHERE ihk_info_page_id = $1
`

func (q *Queries) GetNextInfoVersionNumber(ctx context.Context, ihkInfoPageID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextInfoVersionNumber, ihkInfoPageID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const getPublicIHKBySlug = `-- name: GetPublicIHKBySlug :one
SELECT
  i.id,
  i.name,
  i.slug,
  i.city,
  i.state,
  i.official_url,
  i.is_active,
  i.created_at,
  i.updated_at,
  p.id AS info_page_id,
  p.current_text,
  p.confidence_level,
  p.source_summary,
  p.last_version_id,
  p.locked,
  p.updated_by,
  p.created_at AS info_created_at,
  p.updated_at AS info_updated_at
FROM ihks i
LEFT JOIN ihk_info_pages p ON p.ihk_id = i.id
WHERE i.slug = $1
  AND i.is_active = true
`

type GetPublicIHKBySlugRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	City            *string            `json:"city"`
	State           string             `json:"state"`
	OfficialUrl     *string            `json:"official_url"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	InfoPageID      pgtype.UUID        `json:"info_page_id"`
	CurrentText     *string            `json:"current_text"`
	ConfidenceLevel *string            `json:"confidence_level"`
	SourceSummary   *string            `json:"source_summary"`
	LastVersionID   pgtype.UUID        `json:"last_version_id"`
	Locked          *bool              `json:"locked"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	InfoCreatedAt   pgtype.Timestamptz `json:"info_created_at"`
	InfoUpdatedAt   pgtype.Timestamptz `json:"info_updated_at"`
}

func (q *Queries) GetPublicIHKBySlug(ctx context.Context, slug string) (GetPublicIHKBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicIHKBySlug, slug)
	var i GetPublicIHKBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.City,
		&i.State,
		&i.OfficialUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InfoPageID,
		&i.CurrentText,
		&i.ConfidenceLevel,
		&i.SourceSummary,
		&i.LastVersionID,
		&i.Locked,
		&i.UpdatedBy,
		&i.InfoCreatedAt,
		&i.InfoUpdatedAt,
	)
	return i, err
}

const listAdminIHKs = `-- name: ListAdminIHKs :many
SELECT id, name, slug, city, state, official_url, is_active, created_at, updated_at
FROM (
  SELECT
    i.id,
    i.name,
    i.slug,
    i.city,
    i.state,
    i.official_url,
    i.is_active,
    i.created_at,
    i.updated_at,
    COALESCE(bit_or(a.allow_mask), 0)::bigint AS allow_mask,
    COALESCE(bit_or(a.deny_mask), 0)::bigint AS deny_mask
  FROM ihks i
  JOIN user_role_assignments a ON a.user_id = $1::uuid
    AND (a.expires_at IS NULL OR a.expires_at > now())
    AND (
      a.scope_type = 'global'
      OR (a.scope_type = 'state' AND a.scope_id = i.state)
      OR (a.scope_type = 'ihk' AND a.scope_id = i.id::text)
    )
  WHERE ($2::text IS NULL OR i.state = $2)
    AND (
      $3::text IS NULL
      OR i.name ILIKE ('%' || $3 || '%')
      OR i.slug ILIKE ('%' || $3 || '%')
      OR i.city ILIKE ('%' || $3 || '%')
      OR i.state ILIKE ('%' || $3 || '%')
    )
  GROUP BY i.id, i.name, i.slug, i.city, i.state, i.official_url, i.is_active, i.created_at, i.updated_at
) scoped
WHERE ((allow_mask & ~deny_mask) & $4::bigint) = $4::bigint
  AND (
    $5::text IS NULL
    OR (name > $5 OR (name = $5 AND id > $6::uuid))
  )
ORDER BY name ASC, id ASC
LIMIT $7
`

type ListAdminIHKsParams struct {
	ActorUserID  pgtype.UUID `json:"actor_user_id"`
	State        *string     `json:"state"`
	Query        *string     `json:"query"`
	RequiredMask int64       `json:"required_mask"`
	CursorName   *string     `json:"cursor_name"`
	CursorID     pgtype.UUID `json:"cursor_id"`
	Limit        int32       `json:"limit"`
}

func (q *Queries) ListAdminIHKs(ctx context.Context, arg ListAdminIHKsParams) ([]Ihk, error) {
	rows, err := q.db.Query(ctx, listAdminIHKs,
		arg.ActorUserID,
		arg.State,
		arg.Query,
		arg.RequiredMask,
		arg.CursorName,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ihk
	for rows.Next() {
		var i Ihk
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.City,
			&i.State,
			&i.OfficialUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIHKInfoVersionsByIHKID = `-- name: ListIHKInfoVersionsByIHKID :many
SELECT id, ihk_info_page_id, ihk_id, version_number, old_text, new_text, change_summary, changed_by,
  based_on_info_suggestion_id, created_at
FROM ihk_info_versions
WHERE ihk_id = $1
ORDER BY version_number DESC
`

func (q *Queries) ListIHKInfoVersionsByIHKID(ctx context.Context, ihkID pgtype.UUID) ([]IhkInfoVersion, error) {
	rows, err := q.db.Query(ctx, listIHKInfoVersionsByIHKID, ihkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IhkInfoVersion
	for rows.Next() {
		var i IhkInfoVersion
		if err := rows.Scan(
			&i.ID,
			&i.IhkInfoPageID,
			&i.IhkID,
			&i.VersionNumber,
			&i.OldText,
			&i.NewText,
			&i.ChangeSummary,
			&i.ChangedBy,
			&i.BasedOnInfoSuggestionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicIHKs = `-- name: ListPublicIHKs :many
SELECT
  i.id,
  i.name,
  i.slug,
  i.city,
  i.state,
  i.official_url,
  i.is_active,
  i.created_at,
  i.updated_at,
  p.id AS info_page_id,
  p.current_text,
  p.confidence_level,
  p.source_summary,
  p.last_version_id,
  p.locked,
  p.updated_by,
  p.created_at AS info_created_at,
  p.updated_at AS info_updated_at
FROM ihks i
LEFT JOIN ihk_info_pages p ON p.ihk_id = i.id
WHERE i.is_active = true
  AND ($1::text IS NULL OR i.state = $1)
  AND (
    $2::text IS NULL
    OR i.name ILIKE ('%' || $2 || '%')
    OR i.slug ILIKE ('%' || $2 || '%')
    OR i.city ILIKE ('%' || $2 || '%')
    OR i.state ILIKE ('%' || $2 || '%')
  )
  AND (
    $3::text IS NULL OR
    (i.name > $3 OR (i.name = $3 AND i.id > $4::uuid))
  )
ORDER BY i.name ASC, i.id ASC
LIMIT $5
`

type ListPublicIHKsParams struct {
	State      *string     `json:"state"`
	Query      *string     `json:"query"`
	CursorName *string     `json:"cursor_name"`
	CursorID   pgtype.UUID `json:"cursor_id"`
	Limit      int32       `json:"limit"`
}

type ListPublicIHKsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	City            *string            `json:"city"`
	State           string             `json:"state"`
	OfficialUrl     *string            `json:"official_url"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	InfoPageID      pgtype.UUID        `json:"info_page_id"`
	CurrentText     *string            `json:"current_text"`
	ConfidenceLevel *string            `json:"confidence_level"`
	SourceSummary   *string            `json:"source_summary"`
	LastVersionID   pgtype.UUID        `json:"last_version_id"`
	Locked          *bool              `json:"locked"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	InfoCreatedAt   pgtype.Timestamptz `json:"info_created_at"`
	InfoUpdatedAt   pgtype.Timestamptz `json:"info_updated_at"`
}

func (q *Queries) ListPublicIHKs(ctx context.Context, arg ListPublicIHKsParams) ([]ListPublicIHKsRow, error) {
	rows, err := q.db.Query(ctx, listPublicIHKs,
		arg.State,
		arg.Query,
		arg.CursorName,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicIHKsRow
	for rows.Next() {
		var i ListPublicIHKsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.City,
			&i.State,
			&i.OfficialUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InfoPageID,
			&i.CurrentText,
			&i.ConfidenceLevel,
			&i.SourceSummary,
			&i.LastVersionID,
			&i.Locked,
			&i.UpdatedBy,
			&i.InfoCreatedAt,
			&i.InfoUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIHKInfoPageByIHKID = `-- name: LockIHKInfoPageByIHKID :one
SELECT id, ihk_id, current_text, confidence_level, source_summary, last_version_id, locked, updated_by, created_at, updated_at
FROM ihk_info_pages
WHERE ihk_id = $1
FOR UPDATE
`

func (q *Queries) LockIHKInfoPageByIHKID(ctx context.Context, ihkID pgtype.UUID) (IhkInfoPage, error) {
	row := q.db.QueryRow(ctx, lockIHKInfoPageByIHKID, ihkID)
	var i IhkInfoPage
	err := row.Scan(
		&i.ID,
		&i.IhkID,
		&i.CurrentText,
		&i.ConfidenceLevel,
		&i.SourceSummary,
		&i.LastVersionID,
		&i.Locked,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIHKInfoPage = `-- name: UpdateIHKInfoPage :one
UPDATE ihk_info_pages
SET current_text = $2,
    confidence_level = $3,
    source_summary = $4,
    last_version_id = $5,
    updated_by = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, ihk_id, current_text, confidence_level, source_summary, last_version_id, locked, updated_by, created_at, updated_at
`

type UpdateIHKInfoPageParams struct {
	ID              pgtype.UUID `json:"id"`
	CurrentText     string      `json:"current_text"`
	ConfidenceLevel string      `json:"confidence_level"`
	SourceSummary   *string     `json:"source_summary"`
	LastVersionID   pgtype.UUID `json:"last_version_id"`
	UpdatedBy       pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateIHKInfoPage(ctx context.Context, arg UpdateIHKInfoPageParams) (IhkInfoPage, error) {
	row := q.db.QueryRow(ctx, updateIHKInfoPage,
		arg.ID,
		arg.CurrentText,
		arg.ConfidenceLevel,
		arg.SourceSummary,
		arg.LastVersionID,
		arg.UpdatedBy,
	)
	var i IhkInfoPage
	err := row.Scan(
		&i.ID,
		&i.IhkID,
		&i.CurrentText,
		&i.ConfidenceLevel,
		&i.SourceSummary,
		&i.LastVersionID,
		&i.Locked,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIHKOfficialURL = `-- name: UpdateIHKOfficialURL :one
UPDATE ihks
SET official_url = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, city, state, official_url, is_active, created_at, updated_at
`

type UpdateIHKOfficialURLParams struct {
	ID          pgtype.UUID `json:"id"`
	OfficialUrl *string     `json:"official_url"`
}

func (q *Queries) UpdateIHKOfficialURL(ctx context.Context, arg UpdateIHKOfficialURLParams) (Ihk, error) {
	row := q.db.QueryRow(ctx, updateIHKOfficialURL, arg.ID, arg.OfficialUrl)
	var i Ihk
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.City,
		&i.State,
		&i.OfficialUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCatalogIHK = `-- name: UpsertCatalogIHK :one
INSERT INTO ihks (name, slug, city, state, official_url, is_active)
VALUES ($1, $2, $3, $4, $5, true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  is_active = true,
  updated_at = now()
RETURNING id, name, slug, city, state, official_url, is_active, created_at, updated_at
`

type UpsertCatalogIHKParams struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	City        *string `json:"city"`
	State       string  `json:"state"`
	OfficialUrl *string `json:"official_url"`
}

func (q *Queries) UpsertCatalogIHK(ctx context.Context, arg UpsertCatalogIHKParams) (Ihk, error) {
	row := q.db.QueryRow(ctx, upsertCatalogIHK,
		arg.Name,
		arg.Slug,
		arg.City,
		arg.State,
		arg.OfficialUrl,
	)
	var i Ihk
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.City,
		&i.State,
		&i.OfficialUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
