// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: info_suggestions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInfoSuggestion = `-- name: CreateInfoSuggestion :one
INSERT INTO info_suggestions (
  ihk_id,
  current_text_snapshot,
  suggested_change,
  public_pending_text,
  reason,
  source_url,
  source_note,
  language_code,
  language_confidence,
  pre_moderation_status,
  moderation_flags,
  public_pending_visible,
  public_pending_created_at,
  submitted_by_user_id,
  submitted_email,
  ip_hash,
  status
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11,
  $12, $13, $14, $15, $16,
  $17
)
RETURNING id, ihk_id, current_text_snapshot, suggested_change, public_pending_text, reason, source_url, source_note,
  language_code, language_confidence, pre_moderation_status, moderation_flags,
  public_pending_visible, public_pending_created_at, public_pending_hidden_at, public_pending_hidden_by, public_pending_hide_reason,
  submitted_by_user_id, submitted_email, ip_hash, status, assigned_to, accepted_by, applied_by, created_at, updated_at
`

type CreateInfoSuggestionParams struct {
	IhkID                  pgtype.UUID        `json:"ihk_id"`
	CurrentTextSnapshot    string             `json:"current_text_snapshot"`
	SuggestedChange        string             `json:"suggested_change"`
	PublicPendingText      string             `json:"public_pending_text"`
	Reason                 *string            `json:"reason"`
	SourceUrl              *string            `json:"source_url"`
	SourceNote             *string            `json:"source_note"`
	LanguageCode           string             `json:"language_code"`
	LanguageConfidence     pgtype.Numeric     `json:"language_confidence"`
	PreModerationStatus    string             `json:"pre_moderation_status"`
	ModerationFlags        []byte             `json:"moderation_flags"`
	PublicPendingVisible   bool               `json:"public_pending_visible"`
	PublicPendingCreatedAt pgtype.Timestamptz `json:"public_pending_created_at"`
	SubmittedByUserID      pgtype.UUID        `json:"submitted_by_user_id"`
	SubmittedEmail         *string            `json:"submitted_email"`
	IpHash                 *string            `json:"ip_hash"`
	Status                 string             `json:"status"`
}

func (q *Queries) CreateInfoSuggestion(ctx context.Context, arg CreateInfoSuggestionParams) (InfoSuggestion, error) {
	row := q.db.QueryRow(ctx, createInfoSuggestion,
		arg.IhkID,
		arg.CurrentTextSnapshot,
		arg.SuggestedChange,
		arg.PublicPendingText,
		arg.Reason,
		arg.SourceUrl,
		arg.SourceNote,
		arg.LanguageCode,
		arg.LanguageConfidence,
		arg.PreModerationStatus,
		arg.ModerationFlags,
		arg.PublicPendingVisible,
		arg.PublicPendingCreatedAt,
		arg.SubmittedByUserID,
		arg.SubmittedEmail,
		arg.IpHash,
		arg.Status,
	)
	var i InfoSuggestion
	err := row.Scan(
		&i.ID,
		&i.IhkID,
		&i.CurrentTextSnapshot,
		&i.SuggestedChange,
		&i.PublicPendingText,
		&i.Reason,
		&i.SourceUrl,
		&i.SourceNote,
		&i.LanguageCode,
		&i.LanguageConfidence,
		&i.PreModerationStatus,
		&i.ModerationFlags,
		&i.PublicPendingVisible,
		&i.PublicPendingCreatedAt,
		&i.PublicPendingHiddenAt,
		&i.PublicPendingHiddenBy,
		&i.PublicPendingHideReason,
		&i.SubmittedByUserID,
		&i.SubmittedEmail,
		&i.IpHash,
		&i.Status,
		&i.AssignedTo,
		&i.AcceptedBy,
		&i.AppliedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminInfoSuggestionByID = `-- name: GetAdminInfoSuggestionByID :one
SELECT
  s.id, s.ihk_id, s.current_text_snapshot, s.suggested_change, s.public_pending_text, s.reason, s.source_url, s.source_note, s.language_code, s.language_confidence, s.pre_moderation_status, s.moderation_flags, s.public_pending_visible, s.public_pending_created_at, s.public_pending_hidden_at, s.public_pending_hidden_by, s.public_pending_hide_reason, s.submitted_by_user_id, s.submitted_email, s.ip_hash, s.status, s.assigned_to, s.accepted_by, s.applied_by, s.created_at, s.updated_at,
  i.name AS ihk_name,
  i.slug AS ihk_slug,
  i.state AS ihk_state,
  p.current_text AS live_current_text
FROM info_suggestions s
JOIN ihks i ON i.id = s.ihk_id
JOIN ihk_info_pages p ON p.ihk_id = i.id
WHERE s.id = $1
`

type GetAdminInfoSuggestionByIDRow struct {
	ID                      pgtype.UUID        `json:"id"`
	IhkID                   pgtype.UUID        `json:"ihk_id"`
	CurrentTextSnapshot     string             `json:"current_text_snapshot"`
	SuggestedChange         string             `json:"suggested_change"`
	PublicPendingText       string             `json:"public_pending_text"`
	Reason                  *string            `json:"reason"`
	SourceUrl               *string            `json:"source_url"`
	SourceNote              *string            `json:"source_note"`
	LanguageCode            string             `json:"language_code"`
	LanguageConfidence      pgtype.Numeric     `json:"language_confidence"`
	PreModerationStatus     string             `json:"pre_moderation_status"`
	ModerationFlags         []byte             `json:"moderation_flags"`
	PublicPendingVisible    bool               `json:"public_pending_visible"`
	PublicPendingCreatedAt  pgtype.Timestamptz `json:"public_pending_created_at"`
	PublicPendingHiddenAt   pgtype.Timestamptz `json:"public_pending_hidden_at"`
	PublicPendingHiddenBy   pgtype.UUID        `json:"public_pending_hidden_by"`
	PublicPendingHideReason *string            `json:"public_pending_hide_reason"`
	SubmittedByUserID       pgtype.UUID        `json:"submitted_by_user_id"`
	SubmittedEmail          *string            `json:"submitted_email"`
	IpHash                  *string            `json:"ip_hash"`
	Status                  string             `json:"status"`
	AssignedTo              pgtype.UUID        `json:"assigned_to"`
	AcceptedBy              pgtype.UUID        `json:"accepted_by"`
	AppliedBy               pgtype.UUID        `json:"applied_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	IhkName                 string             `json:"ihk_name"`
	IhkSlug                 string             `json:"ihk_slug"`
	IhkState                string             `json:"ihk_state"`
	LiveCurrentText         string             `json:"live_current_text"`
}

func (q *Queries) GetAdminInfoSuggestionByID(ctx context.Context, id pgtype.UUID) (GetAdminInfoSuggestionByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminInfoSuggestionByID, id)
	var i GetAdminInfoSuggestionByIDRow
	err := row.Scan(
		&i.ID,
		&i.IhkID,
		&i.CurrentTextSnapshot,
		&i.SuggestedChange,
		&i.PublicPendingText,
		&i.Reason,
		&i.SourceUrl,
		&i.SourceNote,
		&i.LanguageCode,
		&i.LanguageConfidence,
		&i.PreModerationStatus,
		&i.ModerationFlags,
		&i.PublicPendingVisible,
		&i.PublicPendingCreatedAt,
		&i.PublicPendingHiddenAt,
		&i.PublicPendingHiddenBy,
		&i.PublicPendingHideReason,
		&i.SubmittedByUserID,
		&i.SubmittedEmail,
		&i.IpHash,
		&i.Status,
		&i.AssignedTo,
		&i.AcceptedBy,
		&i.AppliedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IhkName,
		&i.IhkSlug,
		&i.IhkState,
		&i.LiveCurrentText,
	)
	return i, err
}

const hideInfoSuggestionPending = `-- name: HideInfoSuggestionPending :one
UPDATE info_suggestions
SET public_pending_visible = false,
    public_pending_hidden_at = now(),
    public_pending_hidden_by = $2,
    public_pending_hide_reason = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, ihk_id, current_text_snapshot, suggested_change, public_pending_text, reason, source_url, source_note, language_code, language_confidence, pre_moderation_status, moderation_flags, public_pending_visible, public_pending_created_at, public_pending_hidden_at, public_pending_hidden_by, public_pending_hide_reason, submitted_by_user_id, submitted_email, ip_hash, status, assigned_to, accepted_by, applied_by, created_at, updated_at
`

type HideInfoSuggestionPendingParams struct {
	ID                      pgtype.UUID `json:"id"`
	PublicPendingHiddenBy   pgtype.UUID `json:"public_pending_hidden_by"`
	PublicPendingHideReason *string     `json:"public_pending_hide_reason"`
}

func (q *Queries) HideInfoSuggestionPending(ctx context.Context, arg HideInfoSuggestionPendingParams) (InfoSuggestion, error) {
	row := q.db.QueryRow(ctx, hideInfoSuggestionPending, arg.ID, arg.PublicPendingHiddenBy, arg.PublicPendingHideReason)
	var i InfoSuggestion
	err := row.Scan(
		&i.ID,
		&i.IhkID,
		&i.CurrentTextSnapshot,
		&i.SuggestedChange,
		&i.PublicPendingText,
		&i.Reason,
		&i.SourceUrl,
		&i.SourceNote,
		&i.LanguageCode,
		&i.LanguageConfidence,
		&i.PreModerationStatus,
		&i.ModerationFlags,
		&i.PublicPendingVisible,
		&i.PublicPendingCreatedAt,
		&i.PublicPendingHiddenAt,
		&i.PublicPendingHiddenBy,
		&i.PublicPendingHideReason,
		&i.SubmittedByUserID,
		&i.SubmittedEmail,
		&i.IpHash,
		&i.Status,
		&i.AssignedTo,
		&i.AcceptedBy,
		&i.AppliedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminInfoSuggestions = `-- name: ListAdminInfoSuggestions :many
SELECT s.id, s.ihk_id, i.state AS ihk_state, s.public_pending_visible, s.status, s.created_at
FROM info_suggestions s
JOIN ihks i ON i.id = s.ihk_id
JOIN (
  SELECT
    i2.id AS ihk_id,
    COALESCE(bit_or(a.allow_mask), 0)::bigint AS allow_mask,
    COALESCE(bit_or(a.deny_mask), 0)::bigint AS deny_mask
  FROM ihks i2
  JOIN user_role_assignments a ON a.user_id = $1::uuid
    AND (a.expires_at IS NULL OR a.expires_at > now())
    AND (
      a.scope_type = 'global'
      OR (a.scope_type = 'state' AND a.scope_id = i2.state)
      OR (a.scope_type = 'ihk' AND a.scope_id = i2.id::text)
    )
  GROUP BY i2.id
) scope_mask ON scope_mask.ihk_id = i.id
WHERE ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR ihk_id = $3::uuid)
  AND ($4::bool IS NULL OR public_pending_visible = $4)
  AND ((scope_mask.allow_mask & ~scope_mask.deny_mask) & $5::bigint) = $5::bigint
  AND (
    $6::timestamptz IS NULL OR
    (s.created_at < $6 OR (s.created_at = $6 AND s.id < $7::uuid))
  )
ORDER BY s.created_at DESC, s.id DESC
LIMIT $8
`

type ListAdminInfoSuggestionsParams struct {
	ActorUserID          pgtype.UUID        `json:"actor_user_id"`
	Status               *string            `json:"status"`
	IhkID                pgtype.UUID        `json:"ihk_id"`
	PublicPendingVisible *bool              `json:"public_pending_visible"`
	RequiredMask         int64              `json:"required_mask"`
	CursorCreatedAt      pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID             pgtype.UUID        `json:"cursor_id"`
	Limit                int32              `json:"limit"`
}

type ListAdminInfoSuggestionsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	IhkID                pgtype.UUID        `json:"ihk_id"`
	IhkState             string             `json:"ihk_state"`
	PublicPendingVisible bool               `json:"public_pending_visible"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAdminInfoSuggestions(ctx context.Context, arg ListAdminInfoSuggestionsParams) ([]ListAdminInfoSuggestionsRow, error) {
	rows, err := q.db.Query(ctx, listAdminInfoSuggestions,
		arg.ActorUserID,
		arg.Status,
		arg.IhkID,
		arg.PublicPendingVisible,
		arg.RequiredMask,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminInfoSuggestionsRow
	for rows.Next() {
		var i ListAdminInfoSuggestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.IhkID,
			&i.IhkState,
			&i.PublicPendingVisible,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHintsByIHKID = `-- name: ListPendingHintsByIHKID :many
SELECT id, ihk_id, public_pending_text, source_url, source_note, created_at
FROM info_suggestions
WHERE ihk_id = $1
  AND public_pending_visible = true
  AND status IN ('submitted', 'under_review')
ORDER BY created_at DESC
LIMIT $2
`

type ListPendingHintsByIHKIDParams struct {
	IhkID pgtype.UUID `json:"ihk_id"`
	Limit int32       `json:"limit"`
}

type ListPendingHintsByIHKIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	IhkID             pgtype.UUID        `json:"ihk_id"`
	PublicPendingText string             `json:"public_pending_text"`
	SourceUrl         *string            `json:"source_url"`
	SourceNote        *string            `json:"source_note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingHintsByIHKID(ctx context.Context, arg ListPendingHintsByIHKIDParams) ([]ListPendingHintsByIHKIDRow, error) {
	rows, err := q.db.Query(ctx, listPendingHintsByIHKID, arg.IhkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingHintsByIHKIDRow
	for rows.Next() {
		var i ListPendingHintsByIHKIDRow
		if err := rows.Scan(
			&i.ID,
			&i.IhkID,
			&i.PublicPendingText,
			&i.SourceUrl,
			&i.SourceNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHintsByIHKIDs = `-- name: ListPendingHintsByIHKIDs :many
SELECT h.id, h.ihk_id, h.public_pending_text, h.source_url, h.source_note, h.created_at
FROM unnest($1::uuid[]) AS requested(ihk_id)
JOIN LATERAL (
  SELECT id, ihk_id, public_pending_text, source_url, source_note, created_at
  FROM info_suggestions
  WHERE ihk_id = requested.ihk_id
    AND public_pending_visible = true
    AND status IN ('submitted', 'under_review')
  ORDER BY created_at DESC
  LIMIT $2
) h ON true
ORDER BY h.ihk_id, h.created_at DESC
`

type ListPendingHintsByIHKIDsParams struct {
	IhkIds      []pgtype.UUID `json:"ihk_ids"`
	PerIhkLimit int32         `json:"per_ihk_limit"`
}

type ListPendingHintsByIHKIDsRow struct {
	ID                pgtype.UUID        `json:"id"`
	IhkID             pgtype.UUID        `json:"ihk_id"`
	PublicPendingText string             `json:"public_pending_text"`
	SourceUrl         *string            `json:"source_url"`
	SourceNote        *string            `json:"source_note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingHintsByIHKIDs(ctx context.Context, arg ListPendingHintsByIHKIDsParams) ([]ListPendingHintsByIHKIDsRow, error) {
	rows, err := q.db.Query(ctx, listPendingHintsByIHKIDs, arg.IhkIds, arg.PerIhkLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingHintsByIHKIDsRow
	for rows.Next() {
		var i ListPendingHintsByIHKIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.IhkID,
			&i.PublicPendingText,
			&i.SourceUrl,
			&i.SourceNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInfoSuggestionByID = `-- name: LockInfoSuggestionByID :one
SELECT id, ihk_id, current_text_snapshot, suggested_change, public_pending_text, reason, source_url, source_note, language_code, language_confidence, pre_moderation_status, moderation_flags, public_pending_visible, public_pending_created_at, public_pending_hidden_at, public_pending_hidden_by, public_pending_hide_reason, submitted_by_user_id, submitted_email, ip_hash, status, assigned_to, accepted_by, applied_by, created_at, updated_at
FROM info_suggestions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockInfoSuggestionByID(ctx context.Context, id pgtype.UUID) (InfoSuggestion, error) {
	row := q.db.QueryRow(ctx, lockInfoSuggestionByID, id)
	var i InfoSuggestion
	err := row.Scan(
		&i.ID,
		&i.IhkID,
		&i.CurrentTextSnapshot,
		&i.SuggestedChange,
		&i.PublicPendingText,
		&i.Reason,
		&i.SourceUrl,
		&i.SourceNote,
		&i.LanguageCode,
		&i.LanguageConfidence,
		&i.PreModerationStatus,
		&i.ModerationFlags,
		&i.PublicPendingVisible,
		&i.PublicPendingCreatedAt,
		&i.PublicPendingHiddenAt,
		&i.PublicPendingHiddenBy,
		&i.PublicPendingHideReason,
		&i.SubmittedByUserID,
		&i.SubmittedEmail,
		&i.IpHash,
		&i.Status,
		&i.AssignedTo,
		&i.AcceptedBy,
		&i.AppliedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInfoSuggestionStatus = `-- name: UpdateInfoSuggestionStatus :one
UPDATE info_suggestions
SET status = $2,
    public_pending_visible = $3,
    accepted_by = $4,
    applied_by = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, ihk_id, current_text_snapshot, suggested_change, public_pending_text, reason, source_url, source_note, language_code, language_confidence, pre_moderation_status, moderation_flags, public_pending_visible, public_pending_created_at, public_pending_hidden_at, public_pending_hidden_by, public_pending_hide_reason, submitted_by_user_id, submitted_email, ip_hash, status, assigned_to, accepted_by, applied_by, created_at, updated_at
`

type UpdateInfoSuggestionStatusParams struct {
	ID                   pgtype.UUID `json:"id"`
	Status               string      `json:"status"`
	PublicPendingVisible bool        `json:"public_pending_visible"`
	AcceptedBy           pgtype.UUID `json:"accepted_by"`
	AppliedBy            pgtype.UUID `json:"applied_by"`
}

func (q *Queries) UpdateInfoSuggestionStatus(ctx context.Context, arg UpdateInfoSuggestionStatusParams) (InfoSuggestion, error) {
	row := q.db.QueryRow(ctx, updateInfoSuggestionStatus,
		arg.ID,
		arg.Status,
		arg.PublicPendingVisible,
		arg.AcceptedBy,
		arg.AppliedBy,
	)
	var i InfoSuggestion
	err := row.Scan(
		&i.ID,
		&i.IhkID,
		&i.CurrentTextSnapshot,
		&i.SuggestedChange,
		&i.PublicPendingText,
		&i.Reason,
		&i.SourceUrl,
		&i.SourceNote,
		&i.LanguageCode,
		&i.LanguageConfidence,
		&i.PreModerationStatus,
		&i.ModerationFlags,
		&i.PublicPendingVisible,
		&i.PublicPendingCreatedAt,
		&i.PublicPendingHiddenAt,
		&i.PublicPendingHiddenBy,
		&i.PublicPendingHideReason,
		&i.SubmittedByUserID,
		&i.SubmittedEmail,
		&i.IpHash,
		&i.Status,
		&i.AssignedTo,
		&i.AcceptedBy,
		&i.AppliedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
