// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID            pgtype.UUID        `json:"id"`
	ActorUserID   pgtype.UUID        `json:"actor_user_id"`
	Action        string             `json:"action"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    pgtype.UUID        `json:"resource_id"`
	ScopeType     *string            `json:"scope_type"`
	ScopeID       *string            `json:"scope_id"`
	OldValue      []byte             `json:"old_value"`
	NewValue      []byte             `json:"new_value"`
	IpHash        *string            `json:"ip_hash"`
	UserAgentHash *string            `json:"user_agent_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Ihk struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	City        *string            `json:"city"`
	State       string             `json:"state"`
	OfficialUrl *string            `json:"official_url"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IhkInfoPage struct {
	ID              pgtype.UUID        `json:"id"`
	IhkID           pgtype.UUID        `json:"ihk_id"`
	CurrentText     string             `json:"current_text"`
	ConfidenceLevel string             `json:"confidence_level"`
	SourceSummary   *string            `json:"source_summary"`
	LastVersionID   pgtype.UUID        `json:"last_version_id"`
	Locked          bool               `json:"locked"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type IhkInfoVersion struct {
	ID                      pgtype.UUID        `json:"id"`
	IhkInfoPageID           pgtype.UUID        `json:"ihk_info_page_id"`
	IhkID                   pgtype.UUID        `json:"ihk_id"`
	VersionNumber           int32              `json:"version_number"`
	OldText                 string             `json:"old_text"`
	NewText                 string             `json:"new_text"`
	ChangeSummary           string             `json:"change_summary"`
	ChangedBy               pgtype.UUID        `json:"changed_by"`
	BasedOnInfoSuggestionID pgtype.UUID        `json:"based_on_info_suggestion_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type InfoSuggestion struct {
	ID                      pgtype.UUID        `json:"id"`
	IhkID                   pgtype.UUID        `json:"ihk_id"`
	CurrentTextSnapshot     string             `json:"current_text_snapshot"`
	SuggestedChange         string             `json:"suggested_change"`
	PublicPendingText       string             `json:"public_pending_text"`
	Reason                  *string            `json:"reason"`
	SourceUrl               *string            `json:"source_url"`
	SourceNote              *string            `json:"source_note"`
	LanguageCode            string             `json:"language_code"`
	LanguageConfidence      pgtype.Numeric     `json:"language_confidence"`
	PreModerationStatus     string             `json:"pre_moderation_status"`
	ModerationFlags         []byte             `json:"moderation_flags"`
	PublicPendingVisible    bool               `json:"public_pending_visible"`
	PublicPendingCreatedAt  pgtype.Timestamptz `json:"public_pending_created_at"`
	PublicPendingHiddenAt   pgtype.Timestamptz `json:"public_pending_hidden_at"`
	PublicPendingHiddenBy   pgtype.UUID        `json:"public_pending_hidden_by"`
	PublicPendingHideReason *string            `json:"public_pending_hide_reason"`
	SubmittedByUserID       pgtype.UUID        `json:"submitted_by_user_id"`
	SubmittedEmail          *string            `json:"submitted_email"`
	IpHash                  *string            `json:"ip_hash"`
	Status                  string             `json:"status"`
	AssignedTo              pgtype.UUID        `json:"assigned_to"`
	AcceptedBy              pgtype.UUID        `json:"accepted_by"`
	AppliedBy               pgtype.UUID        `json:"applied_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ModerationTerm struct {
	ID             pgtype.UUID        `json:"id"`
	Term           string             `json:"term"`
	NormalizedTerm string             `json:"normalized_term"`
	Category       string             `json:"category"`
	Severity       string             `json:"severity"`
	IsActive       bool               `json:"is_active"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PermissionRequest struct {
	ID                      pgtype.UUID        `json:"id"`
	UserID                  pgtype.UUID        `json:"user_id"`
	RequestType             string             `json:"request_type"`
	RequestedRoleTemplateID pgtype.UUID        `json:"requested_role_template_id"`
	RequestedScopeType      string             `json:"requested_scope_type"`
	RequestedScopeID        *string            `json:"requested_scope_id"`
	ProofFileName           *string            `json:"proof_file_name"`
	ProofMimeType           *string            `json:"proof_mime_type"`
	ProofContentBase64      *string            `json:"proof_content_base64"`
	ProofNote               *string            `json:"proof_note"`
	Status                  string             `json:"status"`
	ReviewedBy              pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt              pgtype.Timestamptz `json:"reviewed_at"`
	DecisionNote            *string            `json:"decision_note"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ReviewEvent struct {
	ID          pgtype.UUID        `json:"id"`
	TargetType  string             `json:"target_type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	OldStatus   *string            `json:"old_status"`
	NewStatus   *string            `json:"new_status"`
	Comment     *string            `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RoleTemplate struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	AllowMask   int64              `json:"allow_mask"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	IsVerified   bool               `json:"is_verified"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserRoleAssignment struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	RoleTemplateID pgtype.UUID        `json:"role_template_id"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        *string            `json:"scope_id"`
	AllowMask      int64              `json:"allow_mask"`
	DenyMask       int64              `json:"deny_mask"`
	GrantedBy      pgtype.UUID        `json:"granted_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
