// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation_terms.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModerationTerm = `-- name: CreateModerationTerm :one
INSERT INTO moderation_terms (term, normalized_term, category, severity, is_active, created_by)
VALUES ($1, $2, $3, $4, true, $5)
RETURNING id, term, normalized_term, category, severity, is_active, created_by, created_at, updated_at
`

type CreateModerationTermParams struct {
	Term           string      `json:"term"`
	NormalizedTerm string      `json:"normalized_term"`
	Category       string      `json:"category"`
	Severity       string      `json:"severity"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateModerationTerm(ctx context.Context, arg CreateModerationTermParams) (ModerationTerm, error) {
	row := q.db.QueryRow(ctx, createModerationTerm,
		arg.Term,
		arg.NormalizedTerm,
		arg.Category,
		arg.Severity,
		arg.CreatedBy,
	)
	var i ModerationTerm
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.NormalizedTerm,
		&i.Category,
		&i.Severity,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveModerationNormalizedTerms = `-- name: ListActiveModerationNormalizedTerms :many
SELECT normalized_term
FROM moderation_terms
WHERE is_active = true
ORDER BY normalized_term ASC
`

func (q *Queries) ListActiveModerationNormalizedTerms(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveModerationNormalizedTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var normalized_term string
		if err := rows.Scan(&normalized_term); err != nil {
			return nil, err
		}
		items = append(items, normalized_term)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveModerationTerms = `-- name: ListActiveModerationTerms :many
SELECT id, term, normalized_term, category, severity, is_active, created_by, created_at, updated_at
FROM moderation_terms
WHERE is_active = true
ORDER BY severity DESC, category ASC, normalized_term ASC
`

func (q *Queries) ListActiveModerationTerms(ctx context.Context) ([]ModerationTerm, error) {
	rows, err := q.db.Query(ctx, listActiveModerationTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationTerm
	for rows.Next() {
		var i ModerationTerm
		if err := rows.Scan(
			&i.ID,
			&i.Term,
			&i.NormalizedTerm,
			&i.Category,
			&i.Severity,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteModerationTerm = `-- name: SoftDeleteModerationTerm :exec
UPDATE moderation_terms
SET is_active = false
WHERE id = $1
`

func (q *Queries) SoftDeleteModerationTerm(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteModerationTerm, id)
	return err
}

const updateModerationTerm = `-- name: UpdateModerationTerm :one
UPDATE moderation_terms
SET term = COALESCE($1, term),
    normalized_term = COALESCE($2, normalized_term),
    category = COALESCE($3, category),
    severity = COALESCE($4, severity),
    is_active = COALESCE($5, is_active)
WHERE id = $6
RETURNING id, term, normalized_term, category, severity, is_active, created_by, created_at, updated_at
`

type UpdateModerationTermParams struct {
	Term           *string     `json:"term"`
	NormalizedTerm *string     `json:"normalized_term"`
	Category       *string     `json:"category"`
	Severity       *string     `json:"severity"`
	IsActive       *bool       `json:"is_active"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateModerationTerm(ctx context.Context, arg UpdateModerationTermParams) (ModerationTerm, error) {
	row := q.db.QueryRow(ctx, updateModerationTerm,
		arg.Term,
		arg.NormalizedTerm,
		arg.Category,
		arg.Severity,
		arg.IsActive,
		arg.ID,
	)
	var i ModerationTerm
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.NormalizedTerm,
		&i.Category,
		&i.Severity,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
