// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission_requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPermissionRequest = `-- name: CreatePermissionRequest :one
INSERT INTO permission_requests (
  user_id,
  request_type,
  requested_role_template_id,
  requested_scope_type,
  requested_scope_id,
  proof_note,
  status
)
VALUES ($1, $2, $3, $4, $5, $6,  'pending')
RETURNING id, user_id, request_type, requested_role_template_id, requested_scope_type, requested_scope_id, proof_note, status, reviewed_by, reviewed_at, decision_note, created_at, updated_at
`

type CreatePermissionRequestParams struct {
	UserID                  pgtype.UUID `json:"user_id"`
	RequestType             string      `json:"request_type"`
	RequestedRoleTemplateID pgtype.UUID `json:"requested_role_template_id"`
	RequestedScopeType      string      `json:"requested_scope_type"`
	RequestedScopeID        *string     `json:"requested_scope_id"`
	ProofNote               *string     `json:"proof_note"`
}

func (q *Queries) CreatePermissionRequest(ctx context.Context, arg CreatePermissionRequestParams) (PermissionRequest, error) {
	row := q.db.QueryRow(ctx, createPermissionRequest,
		arg.UserID,
		arg.RequestType,
		arg.RequestedRoleTemplateID,
		arg.RequestedScopeType,
		arg.RequestedScopeID,
		arg.ProofNote,
	)
	var i PermissionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestType,
		&i.RequestedRoleTemplateID,
		&i.RequestedScopeType,
		&i.RequestedScopeID,
		&i.ProofNote,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const existsPendingPermissionRequest = `-- name: ExistsPendingPermissionRequest :one
SELECT EXISTS (
  SELECT 1
  FROM permission_requests
  WHERE user_id = $1
    AND requested_role_template_id = $2
    AND requested_scope_type = $3
    AND COALESCE(requested_scope_id, '') = COALESCE($4, '')
    AND status = 'pending'
)
`

type ExistsPendingPermissionRequestParams struct {
	UserID                  pgtype.UUID `json:"user_id"`
	RequestedRoleTemplateID pgtype.UUID `json:"requested_role_template_id"`
	RequestedScopeType      string      `json:"requested_scope_type"`
	RequestedScopeID        *string     `json:"requested_scope_id"`
}

func (q *Queries) ExistsPendingPermissionRequest(ctx context.Context, arg ExistsPendingPermissionRequestParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsPendingPermissionRequest,
		arg.UserID,
		arg.RequestedRoleTemplateID,
		arg.RequestedScopeType,
		arg.RequestedScopeID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getPermissionRequestByID = `-- name: GetPermissionRequestByID :one
SELECT
  pr.id,
  pr.user_id,
  u.email,
  u.display_name,
  pr.request_type,
  pr.requested_role_template_id,
  rt.name AS requested_role_name,
  rt.allow_mask AS requested_allow_mask,
  pr.requested_scope_type,
  pr.requested_scope_id,
  pr.proof_note,
  pr.status,
  pr.reviewed_by,
  pr.reviewed_at,
  pr.decision_note,
  pr.created_at,
  pr.updated_at
FROM permission_requests pr
JOIN users u ON u.id = pr.user_id
JOIN role_templates rt ON rt.id = pr.requested_role_template_id
WHERE pr.id = $1
`

type GetPermissionRequestByIDRow struct {
	ID                      pgtype.UUID        `json:"id"`
	UserID                  pgtype.UUID        `json:"user_id"`
	Email                   string             `json:"email"`
	DisplayName             string             `json:"display_name"`
	RequestType             string             `json:"request_type"`
	RequestedRoleTemplateID pgtype.UUID        `json:"requested_role_template_id"`
	RequestedRoleName       string             `json:"requested_role_name"`
	RequestedAllowMask      int64              `json:"requested_allow_mask"`
	RequestedScopeType      string             `json:"requested_scope_type"`
	RequestedScopeID        *string            `json:"requested_scope_id"`
	ProofNote               *string            `json:"proof_note"`
	Status                  string             `json:"status"`
	ReviewedBy              pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt              pgtype.Timestamptz `json:"reviewed_at"`
	DecisionNote            *string            `json:"decision_note"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPermissionRequestByID(ctx context.Context, id pgtype.UUID) (GetPermissionRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getPermissionRequestByID, id)
	var i GetPermissionRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.RequestType,
		&i.RequestedRoleTemplateID,
		&i.RequestedRoleName,
		&i.RequestedAllowMask,
		&i.RequestedScopeType,
		&i.RequestedScopeID,
		&i.ProofNote,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissionRequestInfoSuggestions = `-- name: ListPermissionRequestInfoSuggestions :many
SELECT id, ihk_id, status, created_at
FROM info_suggestions
WHERE submitted_by_user_id = $1
ORDER BY created_at DESC
LIMIT 25
`

type ListPermissionRequestInfoSuggestionsRow struct {
	ID        pgtype.UUID        `json:"id"`
	IhkID     pgtype.UUID        `json:"ihk_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPermissionRequestInfoSuggestions(ctx context.Context, submittedByUserID pgtype.UUID) ([]ListPermissionRequestInfoSuggestionsRow, error) {
	rows, err := q.db.Query(ctx, listPermissionRequestInfoSuggestions, submittedByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionRequestInfoSuggestionsRow
	for rows.Next() {
		var i ListPermissionRequestInfoSuggestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.IhkID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionRequests = `-- name: ListPermissionRequests :many
SELECT
  pr.id,
  pr.user_id,
  u.email,
  u.display_name,
  pr.request_type,
  pr.requested_role_template_id,
  rt.name AS requested_role_name,
  pr.requested_scope_type,
  pr.proof_note,
  pr.status,
  pr.created_at
FROM permission_requests pr
JOIN users u ON u.id = pr.user_id
JOIN role_templates rt ON rt.id = pr.requested_role_template_id
WHERE ($1::text IS NULL OR pr.status = $1)
ORDER BY pr.created_at DESC, pr.id DESC
LIMIT $2
`

type ListPermissionRequestsParams struct {
	Status *string `json:"status"`
	Limit  int32   `json:"limit"`
}

type ListPermissionRequestsRow struct {
	ID                      pgtype.UUID        `json:"id"`
	UserID                  pgtype.UUID        `json:"user_id"`
	Email                   string             `json:"email"`
	DisplayName             string             `json:"display_name"`
	RequestType             string             `json:"request_type"`
	RequestedRoleTemplateID pgtype.UUID        `json:"requested_role_template_id"`
	RequestedRoleName       string             `json:"requested_role_name"`
	RequestedScopeType      string             `json:"requested_scope_type"`
	ProofNote               *string            `json:"proof_note"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPermissionRequests(ctx context.Context, arg ListPermissionRequestsParams) ([]ListPermissionRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPermissionRequests, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionRequestsRow
	for rows.Next() {
		var i ListPermissionRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.RequestType,
			&i.RequestedRoleTemplateID,
			&i.RequestedRoleName,
			&i.RequestedScopeType,
			&i.ProofNote,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPermissionRequestByID = `-- name: LockPermissionRequestByID :one
SELECT id, user_id, request_type, requested_role_template_id, requested_scope_type, requested_scope_id, proof_note, status, reviewed_by, reviewed_at, decision_note, created_at, updated_at
FROM permission_requests
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockPermissionRequestByID(ctx context.Context, id pgtype.UUID) (PermissionRequest, error) {
	row := q.db.QueryRow(ctx, lockPermissionRequestByID, id)
	var i PermissionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestType,
		&i.RequestedRoleTemplateID,
		&i.RequestedScopeType,
		&i.RequestedScopeID,
		&i.ProofNote,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserActiveVerified = `-- name: SetUserActiveVerified :one
UPDATE users
SET is_active = $2,
    is_verified = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, email, display_name, password_hash, is_verified, is_active, created_at, updated_at
`

type SetUserActiveVerifiedParams struct {
	ID         pgtype.UUID `json:"id"`
	IsActive   bool        `json:"is_active"`
	IsVerified bool        `json:"is_verified"`
}

func (q *Queries) SetUserActiveVerified(ctx context.Context, arg SetUserActiveVerifiedParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActiveVerified, arg.ID, arg.IsActive, arg.IsVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePermissionRequestDecision = `-- name: UpdatePermissionRequestDecision :one
UPDATE permission_requests
SET status = $2,
    reviewed_by = $3,
    reviewed_at = now(),
    decision_note = $4
WHERE id = $1
RETURNING id, user_id, request_type, requested_role_template_id, requested_scope_type, requested_scope_id, proof_note, status, reviewed_by, reviewed_at, decision_note, created_at, updated_at
`

type UpdatePermissionRequestDecisionParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	ReviewedBy   pgtype.UUID `json:"reviewed_by"`
	DecisionNote *string     `json:"decision_note"`
}

func (q *Queries) UpdatePermissionRequestDecision(ctx context.Context, arg UpdatePermissionRequestDecisionParams) (PermissionRequest, error) {
	row := q.db.QueryRow(ctx, updatePermissionRequestDecision,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.DecisionNote,
	)
	var i PermissionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestType,
		&i.RequestedRoleTemplateID,
		&i.RequestedScopeType,
		&i.RequestedScopeID,
		&i.ProofNote,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
