// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserRoleAssignment = `-- name: CreateUserRoleAssignment :one
INSERT INTO user_role_assignments (
  user_id, role_template_id, scope_type, scope_id, allow_mask, deny_mask, granted_by, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, role_template_id, scope_type, scope_id, allow_mask, deny_mask, granted_by, expires_at, created_at
`

type CreateUserRoleAssignmentParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	RoleTemplateID pgtype.UUID        `json:"role_template_id"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        *string            `json:"scope_id"`
	AllowMask      int64              `json:"allow_mask"`
	DenyMask       int64              `json:"deny_mask"`
	GrantedBy      pgtype.UUID        `json:"granted_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserRoleAssignment(ctx context.Context, arg CreateUserRoleAssignmentParams) (UserRoleAssignment, error) {
	row := q.db.QueryRow(ctx, createUserRoleAssignment,
		arg.UserID,
		arg.RoleTemplateID,
		arg.ScopeType,
		arg.ScopeID,
		arg.AllowMask,
		arg.DenyMask,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	var i UserRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleTemplateID,
		&i.ScopeType,
		&i.ScopeID,
		&i.AllowMask,
		&i.DenyMask,
		&i.GrantedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserRoleAssignment = `-- name: DeleteUserRoleAssignment :one
DELETE FROM user_role_assignments
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, role_template_id, scope_type, scope_id, allow_mask, deny_mask, granted_by, expires_at, created_at
`

type DeleteUserRoleAssignmentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserRoleAssignment(ctx context.Context, arg DeleteUserRoleAssignmentParams) (UserRoleAssignment, error) {
	row := q.db.QueryRow(ctx, deleteUserRoleAssignment, arg.ID, arg.UserID)
	var i UserRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleTemplateID,
		&i.ScopeType,
		&i.ScopeID,
		&i.AllowMask,
		&i.DenyMask,
		&i.GrantedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleTemplateByID = `-- name: GetRoleTemplateByID :one
SELECT id, name, description, allow_mask, created_at, updated_at
FROM role_templates
WHERE id = $1
`

func (q *Queries) GetRoleTemplateByID(ctx context.Context, id pgtype.UUID) (RoleTemplate, error) {
	row := q.db.QueryRow(ctx, getRoleTemplateByID, id)
	var i RoleTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AllowMask,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleTemplateByName = `-- name: GetRoleTemplateByName :one
SELECT id, name, description, allow_mask, created_at, updated_at
FROM role_templates
WHERE name = $1
`

func (q *Queries) GetRoleTemplateByName(ctx context.Context, name string) (RoleTemplate, error) {
	row := q.db.QueryRow(ctx, getRoleTemplateByName, name)
	var i RoleTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AllowMask,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoleAssignmentsByUser = `-- name: ListRoleAssignmentsByUser :many
SELECT a.scope_type, COALESCE(a.scope_id, '') AS scope_id, a.allow_mask, a.deny_mask
FROM user_role_assignments a
JOIN users u ON u.id = a.user_id
WHERE a.user_id = $1
  AND u.is_active = true
  AND (a.expires_at IS NULL OR a.expires_at > now())
ORDER BY a.created_at ASC
`

type ListRoleAssignmentsByUserRow struct {
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	AllowMask int64  `json:"allow_mask"`
	DenyMask  int64  `json:"deny_mask"`
}

func (q *Queries) ListRoleAssignmentsByUser(ctx context.Context, userID pgtype.UUID) ([]ListRoleAssignmentsByUserRow, error) {
	rows, err := q.db.Query(ctx, listRoleAssignmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoleAssignmentsByUserRow
	for rows.Next() {
		var i ListRoleAssignmentsByUserRow
		if err := rows.Scan(
			&i.ScopeType,
			&i.ScopeID,
			&i.AllowMask,
			&i.DenyMask,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleTemplates = `-- name: ListRoleTemplates :many
SELECT id, name, description, allow_mask, created_at, updated_at
FROM role_templates
ORDER BY name ASC
`

func (q *Queries) ListRoleTemplates(ctx context.Context) ([]RoleTemplate, error) {
	rows, err := q.db.Query(ctx, listRoleTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleTemplate
	for rows.Next() {
		var i RoleTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AllowMask,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleAssignmentsDetailed = `-- name: ListUserRoleAssignmentsDetailed :many
SELECT
  a.id,
  a.user_id,
  a.role_template_id,
  t.name AS role_name,
  a.scope_type,
  a.scope_id,
  a.allow_mask,
  a.deny_mask,
  a.granted_by,
  a.expires_at,
  a.created_at
FROM user_role_assignments a
JOIN role_templates t ON t.id = a.role_template_id
WHERE a.user_id = $1
ORDER BY a.created_at DESC
`

type ListUserRoleAssignmentsDetailedRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	RoleTemplateID pgtype.UUID        `json:"role_template_id"`
	RoleName       string             `json:"role_name"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        *string            `json:"scope_id"`
	AllowMask      int64              `json:"allow_mask"`
	DenyMask       int64              `json:"deny_mask"`
	GrantedBy      pgtype.UUID        `json:"granted_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUserRoleAssignmentsDetailed(ctx context.Context, userID pgtype.UUID) ([]ListUserRoleAssignmentsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listUserRoleAssignmentsDetailed, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRoleAssignmentsDetailedRow
	for rows.Next() {
		var i ListUserRoleAssignmentsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleTemplateID,
			&i.RoleName,
			&i.ScopeType,
			&i.ScopeID,
			&i.AllowMask,
			&i.DenyMask,
			&i.GrantedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userHasActiveRoleTemplateAssignment = `-- name: UserHasActiveRoleTemplateAssignment :one
SELECT EXISTS (
  SELECT 1
  FROM user_role_assignments
  WHERE user_id = $1
    AND role_template_id = $2
    AND scope_type = $3
    AND COALESCE(scope_id, '') = COALESCE($4, '')
    AND (expires_at IS NULL OR expires_at > now())
)
`

type UserHasActiveRoleTemplateAssignmentParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	RoleTemplateID pgtype.UUID `json:"role_template_id"`
	ScopeType      string      `json:"scope_type"`
	ScopeID        *string     `json:"scope_id"`
}

func (q *Queries) UserHasActiveRoleTemplateAssignment(ctx context.Context, arg UserHasActiveRoleTemplateAssignmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasActiveRoleTemplateAssignment,
		arg.UserID,
		arg.RoleTemplateID,
		arg.ScopeType,
		arg.ScopeID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
