// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listReviewEvents = `-- name: ListReviewEvents :many
SELECT id, target_type, target_id, actor_user_id, action, old_status, new_status, comment, created_at
FROM review_events
WHERE target_type = $1
  AND target_id = $2
ORDER BY created_at ASC, id ASC
`

type ListReviewEventsParams struct {
	TargetType string      `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
}

func (q *Queries) ListReviewEvents(ctx context.Context, arg ListReviewEventsParams) ([]ReviewEvent, error) {
	rows, err := q.db.Query(ctx, listReviewEvents, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewEvent
	for rows.Next() {
		var i ReviewEvent
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.ActorUserID,
			&i.Action,
			&i.OldStatus,
			&i.NewStatus,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
