package ihk_catalog

type Entry struct {
	Slug        string
	Name        string
	City        string
	State       string
	OfficialURL string
}

func All() []Entry {
	return []Entry{
		{Slug: "ihk-aachen", Name: "Industrie- und Handelskammer Aachen", City: "Aachen", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/aachen"},
		{Slug: "ihk-arnsberg-hellweg-sauerland", Name: "Industrie- und Handelskammer Arnsberg, Hellweg-Sauerland", City: "Arnsberg", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/arnsberg"},
		{Slug: "ihk-aschaffenburg", Name: "Industrie- und Handelskammer Aschaffenburg", City: "Aschaffenburg", State: "Bayern", OfficialURL: "https://www.ihk.de/aschaffenburg"},
		{Slug: "ihk-schwaben", Name: "Industrie- und Handelskammer Schwaben", City: "Augsburg", State: "Bayern", OfficialURL: "https://www.ihk.de/schwaben"},
		{Slug: "ihk-oberfranken-bayreuth", Name: "Industrie- und Handelskammer für Oberfranken Bayreuth", City: "Bayreuth", State: "Bayern", OfficialURL: "https://www.ihk.de/bayreuth"},
		{Slug: "ihk-berlin", Name: "Industrie- und Handelskammer zu Berlin", City: "Berlin", State: "Berlin", OfficialURL: "https://www.ihk.de/berlin"},
		{Slug: "ihk-ostwestfalen-bielefeld", Name: "Industrie- und Handelskammer Ostwestfalen zu Bielefeld", City: "Bielefeld", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/ostwestfalen"},
		{Slug: "ihk-mittleres-ruhrgebiet", Name: "Industrie- und Handelskammer Mittleres Ruhrgebiet", City: "Bochum", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/bochum"},
		{Slug: "ihk-bonn-rhein-sieg", Name: "Industrie- und Handelskammer Bonn/Rhein-Sieg", City: "Bonn", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/bonn"},
		{Slug: "ihk-braunschweig", Name: "Industrie- und Handelskammer Braunschweig", City: "Braunschweig", State: "Niedersachsen", OfficialURL: "https://www.ihk.de/braunschweig"},
		{Slug: "handelskammer-bremen", Name: "Handelskammer Bremen - IHK für Bremen und Bremerhaven", City: "Bremen", State: "Bremen", OfficialURL: "https://www.ihk.de/bremen"},
		{Slug: "ihk-chemnitz", Name: "Industrie- und Handelskammer Chemnitz", City: "Chemnitz", State: "Sachsen", OfficialURL: "https://www.ihk.de/chemnitz"},
		{Slug: "ihk-coburg", Name: "Industrie- und Handelskammer zu Coburg", City: "Coburg", State: "Bayern", OfficialURL: "https://www.ihk.de/coburg"},
		{Slug: "ihk-cottbus", Name: "Industrie- und Handelskammer Cottbus", City: "Cottbus", State: "Brandenburg", OfficialURL: "https://www.ihk.de/cottbus"},
		{Slug: "ihk-darmstadt-rhein-main-neckar", Name: "Industrie- und Handelskammer Darmstadt Rhein Main Neckar", City: "Darmstadt", State: "Hessen", OfficialURL: "https://www.ihk.de/darmstadt"},
		{Slug: "ihk-lippe-detmold", Name: "Industrie- und Handelskammer Lippe zu Detmold", City: "Detmold", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/lippe-detmold"},
		{Slug: "ihk-lahn-dill", Name: "Industrie- und Handelskammer Lahn-Dill", City: "Dillenburg", State: "Hessen", OfficialURL: "https://www.ihk.de/lahn-dill"},
		{Slug: "ihk-dortmund", Name: "Industrie- und Handelskammer zu Dortmund", City: "Dortmund", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/dortmund"},
		{Slug: "ihk-dresden", Name: "Industrie- und Handelskammer Dresden", City: "Dresden", State: "Sachsen", OfficialURL: "https://www.ihk.de/dresden"},
		{Slug: "ihk-niederrhein", Name: "Niederrheinische Industrie- und Handelskammer Duisburg-Wesel-Kleve zu Duisburg", City: "Duisburg", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/niederrhein"},
		{Slug: "ihk-duesseldorf", Name: "Industrie- und Handelskammer zu Düsseldorf", City: "Düsseldorf", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/duesseldorf"},
		{Slug: "ihk-ostfriesland-papenburg", Name: "Industrie- und Handelskammer für Ostfriesland und Papenburg", City: "Emden", State: "Niedersachsen", OfficialURL: "https://www.ihk.de/emden"},
		{Slug: "ihk-erfurt", Name: "Industrie- und Handelskammer Erfurt", City: "Erfurt", State: "Thüringen", OfficialURL: "https://www.ihk.de/erfurt"},
		{Slug: "ihk-essen-muelheim-oberhausen", Name: "Industrie- und Handelskammer für Essen, Mülheim an der Ruhr, Oberhausen zu Essen", City: "Essen", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/essen"},
		{Slug: "ihk-flensburg", Name: "Industrie- und Handelskammer zu Flensburg", City: "Flensburg", State: "Schleswig-Holstein", OfficialURL: "https://www.ihk.de/flensburg"},
		{Slug: "ihk-frankfurt-am-main", Name: "Industrie- und Handelskammer Frankfurt am Main", City: "Frankfurt am Main", State: "Hessen", OfficialURL: "https://www.ihk.de/frankfurt"},
		{Slug: "ihk-ostbrandenburg", Name: "Industrie- und Handelskammer Ostbrandenburg", City: "Frankfurt (Oder)", State: "Brandenburg", OfficialURL: "https://www.ihk.de/ostbrandenburg"},
		{Slug: "ihk-suedlicher-oberrhein", Name: "Industrie- und Handelskammer Südlicher Oberrhein", City: "Freiburg im Breisgau", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/freiburg"},
		{Slug: "ihk-fulda", Name: "Industrie- und Handelskammer Fulda", City: "Fulda", State: "Hessen", OfficialURL: "https://www.ihk.de/fulda"},
		{Slug: "ihk-ostthueringen-gera", Name: "Industrie- und Handelskammer Ostthüringen zu Gera", City: "Gera", State: "Thüringen", OfficialURL: "https://www.ihk.de/gera"},
		{Slug: "ihk-giessen-friedberg", Name: "Industrie- und Handelskammer Gießen-Friedberg", City: "Gießen", State: "Hessen", OfficialURL: "https://www.ihk.de/giessen-friedberg"},
		{Slug: "sihk-hagen", Name: "Südwestfälische Industrie- und Handelskammer zu Hagen", City: "Hagen", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/hagen"},
		{Slug: "ihk-halle-dessau", Name: "Industrie- und Handelskammer Halle-Dessau", City: "Halle (Saale)", State: "Sachsen-Anhalt", OfficialURL: "https://www.ihk.de/halle"},
		{Slug: "handelskammer-hamburg", Name: "Handelskammer Hamburg", City: "Hamburg", State: "Hamburg", OfficialURL: "https://www.ihk.de/hamburg"},
		{Slug: "ihk-hanau-gelnhausen-schluechtern", Name: "Industrie- und Handelskammer Hanau-Gelnhausen-Schlüchtern", City: "Hanau", State: "Hessen", OfficialURL: "https://www.ihk.de/hanau"},
		{Slug: "ihk-hannover", Name: "Industrie- und Handelskammer Hannover", City: "Hannover", State: "Niedersachsen", OfficialURL: "https://www.ihk.de/hannover"},
		{Slug: "ihk-ostwuerttemberg", Name: "Industrie- und Handelskammer Ostwürttemberg", City: "Heidenheim an der Brenz", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/ostwuerttemberg"},
		{Slug: "ihk-heilbronn-franken", Name: "Industrie- und Handelskammer Heilbronn-Franken", City: "Heilbronn", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/heilbronn"},
		{Slug: "ihk-karlsruhe", Name: "Industrie- und Handelskammer Karlsruhe", City: "Karlsruhe", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/karlsruhe"},
		{Slug: "ihk-kassel-marburg", Name: "Industrie- und Handelskammer Kassel-Marburg", City: "Kassel", State: "Hessen", OfficialURL: "https://www.ihk.de/kassel-marburg"},
		{Slug: "ihk-kiel", Name: "Industrie- und Handelskammer zu Kiel", City: "Kiel", State: "Schleswig-Holstein", OfficialURL: "https://www.ihk.de/kiel"},
		{Slug: "ihk-koblenz", Name: "Industrie- und Handelskammer zu Koblenz", City: "Koblenz", State: "Rheinland-Pfalz", OfficialURL: "https://www.ihk.de/koblenz"},
		{Slug: "ihk-koeln", Name: "Industrie- und Handelskammer zu Köln", City: "Köln", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/koeln"},
		{Slug: "ihk-hochrhein-bodensee", Name: "Industrie- und Handelskammer Hochrhein-Bodensee", City: "Konstanz", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/konstanz"},
		{Slug: "ihk-mittlerer-niederrhein", Name: "Industrie- und Handelskammer Mittlerer Niederrhein", City: "Krefeld", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/mittlerer-niederrhein"},
		{Slug: "ihk-leipzig", Name: "Industrie- und Handelskammer zu Leipzig", City: "Leipzig", State: "Sachsen", OfficialURL: "https://www.ihk.de/leipzig"},
		{Slug: "ihk-limburg", Name: "Industrie- und Handelskammer Limburg", City: "Limburg an der Lahn", State: "Hessen", OfficialURL: "https://www.ihk.de/limburg"},
		{Slug: "ihk-luebeck", Name: "Industrie- und Handelskammer zu Lübeck", City: "Lübeck", State: "Schleswig-Holstein", OfficialURL: "https://www.ihk.de/luebeck"},
		{Slug: "ihk-pfalz", Name: "Industrie- und Handelskammer für die Pfalz", City: "Ludwigshafen am Rhein", State: "Rheinland-Pfalz", OfficialURL: "https://www.ihk.de/pfalz"},
		{Slug: "ihk-lueneburg-wolfsburg", Name: "Industrie- und Handelskammer Lüneburg-Wolfsburg", City: "Lüneburg", State: "Niedersachsen", OfficialURL: "https://www.ihk.de/lueneburg"},
		{Slug: "ihk-magdeburg", Name: "Industrie- und Handelskammer Magdeburg", City: "Magdeburg", State: "Sachsen-Anhalt", OfficialURL: "https://www.ihk.de/magdeburg"},
		{Slug: "ihk-rheinhessen", Name: "Industrie- und Handelskammer für Rheinhessen", City: "Mainz", State: "Rheinland-Pfalz", OfficialURL: "https://www.ihk.de/rheinhessen"},
		{Slug: "ihk-rhein-neckar", Name: "Industrie- und Handelskammer Rhein-Neckar", City: "Mannheim", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/rhein-neckar"},
		{Slug: "ihk-muenchen-oberbayern", Name: "Industrie- und Handelskammer für München und Oberbayern", City: "München", State: "Bayern", OfficialURL: "https://www.ihk-muenchen.de"},
		{Slug: "ihk-nord-westfalen", Name: "Industrie- und Handelskammer Nord Westfalen", City: "Münster", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/nordwestfalen"},
		{Slug: "ihk-neubrandenburg", Name: "Industrie- und Handelskammer zu Neubrandenburg", City: "Neubrandenburg", State: "Mecklenburg-Vorpommern", OfficialURL: "https://www.ihk.de/neubrandenburg"},
		{Slug: "ihk-nuernberg-mittelfranken", Name: "Industrie- und Handelskammer Nürnberg für Mittelfranken", City: "Nürnberg", State: "Bayern", OfficialURL: "https://www.ihk.de/nuernberg"},
		{Slug: "ihk-offenbach", Name: "Industrie- und Handelskammer Offenbach am Main", City: "Offenbach am Main", State: "Hessen", OfficialURL: "https://www.ihk.de/offenbach"},
		{Slug: "oldenburgische-ihk", Name: "Oldenburgische Industrie- und Handelskammer", City: "Oldenburg (Oldenburg)", State: "Niedersachsen", OfficialURL: "https://www.ihk.de/oldenburg"},
		{Slug: "ihk-osnabrueck-emsland-grafschaft-bentheim", Name: "Industrie- und Handelskammer Osnabrück-Emsland-Grafschaft Bentheim", City: "Osnabrück", State: "Niedersachsen", OfficialURL: "https://www.ihk.de/osnabrueck"},
		{Slug: "ihk-niederbayern", Name: "Industrie- und Handelskammer für Niederbayern in Passau", City: "Passau", State: "Bayern", OfficialURL: "https://www.ihk.de/niederbayern"},
		{Slug: "ihk-nordschwarzwald", Name: "Industrie- und Handelskammer Nordschwarzwald", City: "Pforzheim", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/nordschwarzwald"},
		{Slug: "ihk-potsdam", Name: "Industrie- und Handelskammer Potsdam", City: "Potsdam", State: "Brandenburg", OfficialURL: "https://www.ihk.de/potsdam"},
		{Slug: "ihk-regensburg-oberpfalz-kelheim", Name: "Industrie- und Handelskammer Regensburg für Oberpfalz/Kelheim", City: "Regensburg", State: "Bayern", OfficialURL: "https://www.ihk.de/regensburg"},
		{Slug: "ihk-reutlingen", Name: "Industrie- und Handelskammer Reutlingen", City: "Reutlingen", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/reutlingen"},
		{Slug: "ihk-rostock", Name: "Industrie- und Handelskammer zu Rostock", City: "Rostock", State: "Mecklenburg-Vorpommern", OfficialURL: "https://www.ihk.de/rostock"},
		{Slug: "ihk-saarland", Name: "Industrie- und Handelskammer des Saarlandes", City: "Saarbrücken", State: "Saarland", OfficialURL: "https://www.saarland.ihk.de"},
		{Slug: "ihk-schwerin", Name: "Industrie- und Handelskammer zu Schwerin", City: "Schwerin", State: "Mecklenburg-Vorpommern", OfficialURL: "https://www.ihk.de/schwerin"},
		{Slug: "ihk-siegen", Name: "Industrie- und Handelskammer Siegen", City: "Siegen", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/siegen"},
		{Slug: "ihk-stade-elbe-weser", Name: "Industrie- und Handelskammer Stade für den Elbe-Weser-Raum", City: "Stade", State: "Niedersachsen", OfficialURL: "https://www.ihk.de/stade"},
		{Slug: "ihk-region-stuttgart", Name: "Industrie- und Handelskammer Region Stuttgart", City: "Stuttgart", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/stuttgart"},
		{Slug: "ihk-suedthueringen", Name: "Industrie- und Handelskammer Südthüringen", City: "Suhl", State: "Thüringen", OfficialURL: "https://www.ihk.de/suedthueringen"},
		{Slug: "ihk-trier", Name: "Industrie- und Handelskammer Trier", City: "Trier", State: "Rheinland-Pfalz", OfficialURL: "https://www.ihk.de/trier"},
		{Slug: "ihk-ulm", Name: "Industrie- und Handelskammer Ulm", City: "Ulm", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/ulm"},
		{Slug: "ihk-schwarzwald-baar-heuberg", Name: "Industrie- und Handelskammer Schwarzwald-Baar-Heuberg", City: "Villingen-Schwenningen", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/sbh"},
		{Slug: "ihk-bodensee-oberschwaben", Name: "Industrie- und Handelskammer Bodensee-Oberschwaben", City: "Weingarten", State: "Baden-Württemberg", OfficialURL: "https://www.ihk.de/bodensee-oberschwaben"},
		{Slug: "ihk-wiesbaden", Name: "Industrie- und Handelskammer Wiesbaden", City: "Wiesbaden", State: "Hessen", OfficialURL: "https://www.ihk.de/wiesbaden"},
		{Slug: "bergische-ihk", Name: "Bergische Industrie- und Handelskammer Wuppertal-Solingen-Remscheid", City: "Wuppertal", State: "Nordrhein-Westfalen", OfficialURL: "https://www.ihk.de/bergische"},
		{Slug: "ihk-wuerzburg-schweinfurt", Name: "Industrie- und Handelskammer Würzburg-Schweinfurt", City: "Würzburg", State: "Bayern", OfficialURL: "https://www.ihk.de/wuerzburg"},
	}
}
